"""Add mode field to User model

Revision ID: b9f484586239
Revises: e15b603034e3
Create Date: 2026-02-09 16:08:56.430358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f484586239'
down_revision: Union[str, None] = 'e15b603034e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mode', sa.String(length=50), nullable=False, server_default='writer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mode')
    # ### end Alembic commands ###
