"""initial_schema

Revision ID: 454fe1b2dbfb
Revises: eb235f5e9548
Create Date: 2026-02-02 16:08:08.501363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454fe1b2dbfb'
down_revision: Union[str, None] = 'eb235f5e9548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
