"""add FK indexes

Revision ID: f58bd25ccf34
Revises: c3a1f7e82d01
Create Date: 2026-02-21 04:35:27.190841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58bd25ccf34'
down_revision: Union[str, None] = 'c3a1f7e82d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_novel_chapter_type'), table_name='analyses')
    op.create_index(op.f('ix_analyses_chapter_id'), 'analyses', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_analyses_novel_id'), 'analyses', ['novel_id'], unique=False)
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_index(op.f('ix_character_chat_messages_room_id'), 'character_chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_character_chat_rooms_chapter_id'), 'character_chat_rooms', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_character_chat_rooms_novel_id'), 'character_chat_rooms', ['novel_id'], unique=False)
    op.create_index(op.f('ix_character_chat_rooms_user_id'), 'character_chat_rooms', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_histories', 'novels', ['novel_id'], ['id'])
    op.create_index(op.f('ix_vector_documents_chapter_id'), 'vector_documents', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_vector_documents_novel_id'), 'vector_documents', ['novel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_documents_novel_id'), table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_chapter_id'), table_name='vector_documents')
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_index(op.f('ix_character_chat_rooms_user_id'), table_name='character_chat_rooms')
    op.drop_index(op.f('ix_character_chat_rooms_novel_id'), table_name='character_chat_rooms')
    op.drop_index(op.f('ix_character_chat_rooms_chapter_id'), table_name='character_chat_rooms')
    op.drop_index(op.f('ix_character_chat_messages_room_id'), table_name='character_chat_messages')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_analyses_novel_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_chapter_id'), table_name='analyses')
    op.create_index(op.f('ix_analyses_novel_chapter_type'), 'analyses', ['novel_id', 'chapter_id', 'analysis_type'], unique=False)
    # ### end Alembic commands ###
