"""fix_sync

Revision ID: eb235f5e9548
Revises: e15b603034e3
Create Date: 2026-02-02 16:05:58.256115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb235f5e9548'
down_revision: Union[str, None] = 'e15b603034e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('novel')
    op.drop_table('scenes')
    op.add_column('novels', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('novels', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('novels', sa.Column('custom_prompt', sa.Text(), nullable=True))
    op.add_column('novels', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('novels', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('novels', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('novels', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('novels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_foreign_key(None, 'novels', 'users', ['author_id'], ['id'])
    op.drop_column('novels', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'novels', type_='foreignkey')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.alter_column('novels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('novels', 'updated_at')
    op.drop_column('novels', 'is_completed')
    op.drop_column('novels', 'is_public')
    op.drop_column('novels', 'author_id')
    op.drop_column('novels', 'custom_prompt')
    op.drop_column('novels', 'genre')
    op.drop_column('novels', 'description')
    op.create_table('scenes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scene_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name='scenes_novel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scenes_pkey')
    )
    op.create_table('novel',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('similarity', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('hit_rate', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='novel_pkey')
    )
    # ### end Alembic commands ###
