"""dynamic_analysis_jsonb

Revision ID: e15b603034e3
Revises: 
Create Date: 2026-01-29 19:52:09.510627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e15b603034e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('novels', sa.Column('custom_prompt', sa.Text(), nullable=True))
    op.drop_constraint('vector_documents_vector_id_key', 'vector_documents', type_='unique')
    op.create_index(op.f('ix_vector_documents_id'), 'vector_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vector_documents_vector_id'), 'vector_documents', ['vector_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_documents_vector_id'), table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_id'), table_name='vector_documents')
    op.create_unique_constraint('vector_documents_vector_id_key', 'vector_documents', ['vector_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('novels', 'custom_prompt')
    op.alter_column('analyses', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
