"""rename_user_mode_column

Revision ID: 9f1b46a72e36
Revises: b9f484586239
Create Date: 2026-02-11 11:45:13.377084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1b46a72e36'
down_revision: Union[str, None] = 'b9f484586239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mode', new_column_name='user_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_mode', new_column_name='mode')
    # ### end Alembic commands ###
